apiVersion: v1
kind: Service
metadata:
  name: pgsql-prometheus-exporter
  labels:
    app: pgsql-prometheus-exporter
spec:
  selector:
    app: pgsql-prometheus-exporter
  ports:
    - name: prometheus
      protocol: TCP
      port: 9042
      targetPort: 9042